import { get, post } from '../utils/api.js'

// 表情指令 API（通过后端代理转发到 TShock /data/emoji/*）

export async function getEmoteConfig() {
  const res = await get('/api/tshock/data/emoji/config')
  return res.json()
}

export async function saveEmoteConfig(config) {
  const res = await post('/api/tshock/data/emoji/config/set', { config: JSON.stringify(config) })
  return res.json()
}

// 完整表情预设（0~150，共 151 个）。
// 数据来源：Terraria 客户端 EmoteID.cs（ID） + 官方 zh-Hans 本地化 EmojiName（中文名）
export const EMOTE_PRESETS = [
  { id: 0, name: '爱心' },
  { id: 1, name: '愤怒' },
  { id: 2, name: '哭泣' },
  { id: 3, name: '警告' },
  { id: 4, name: '下雨' },
  { id: 5, name: '闪电' },
  { id: 6, name: '彩虹' },
  { id: 7, name: '戒指' },
  { id: 8, name: '毒药' },
  { id: 9, name: '燃烧' },
  { id: 10, name: '沉默' },
  { id: 11, name: '诅咒' },
  { id: 12, name: '蜜蜂' },
  { id: 13, name: '史莱姆' },
  { id: 14, name: '树' },
  { id: 15, name: '大笑' },
  { id: 16, name: '害怕' },
  { id: 17, name: '音乐' },
  { id: 18, name: '血月' },
  { id: 19, name: '日食' },
  { id: 20, name: '南瓜月' },
  { id: 21, name: '霜月' },
  { id: 22, name: '天空' },
  { id: 23, name: '地表' },
  { id: 24, name: '丛林' },
  { id: 25, name: '猩红' },
  { id: 26, name: '腐化' },
  { id: 27, name: '神圣' },
  { id: 28, name: '沙漠' },
  { id: 29, name: '沙滩' },
  { id: 30, name: '岩石生物群系' },
  { id: 31, name: '熔岩生物群系' },
  { id: 32, name: '雪原' },
  { id: 33, name: '剪刀赢' },
  { id: 34, name: '石头赢' },
  { id: 35, name: '布赢' },
  { id: 36, name: '剪刀' },
  { id: 37, name: '石头' },
  { id: 38, name: '布' },
  { id: 39, name: '克苏鲁之眼' },
  { id: 40, name: '世界吞噬怪' },
  { id: 41, name: '克苏鲁之脑' },
  { id: 42, name: '蜂王' },
  { id: 43, name: '骷髅王' },
  { id: 44, name: '血肉墙' },
  { id: 45, name: '毁灭者' },
  { id: 46, name: '机械骷髅王' },
  { id: 47, name: '双子魔眼' },
  { id: 48, name: '世纪之花' },
  { id: 49, name: '石巨人' },
  { id: 50, name: '猪龙鱼' },
  { id: 51, name: '史莱姆王' },
  { id: 52, name: '邪教徒' },
  { id: 53, name: '月亮领主' },
  { id: 54, name: '哀木' },
  { id: 55, name: '南瓜王' },
  { id: 56, name: '常绿尖叫怪' },
  { id: 57, name: '冰雪女王' },
  { id: 58, name: '圣诞坦克' },
  { id: 59, name: '海盗船' },
  { id: 60, name: '火星飞船' },
  { id: 61, name: '僵尸' },
  { id: 62, name: '兔兔' },
  { id: 63, name: '蝴蝶' },
  { id: 64, name: '哥布林' },
  { id: 65, name: '神射手' },
  { id: 66, name: '雪人' },
  { id: 67, name: '蜘蛛' },
  { id: 68, name: '鸟' },
  { id: 69, name: '老鼠' },
  { id: 70, name: '金鱼' },
  { id: 71, name: '火星人' },
  { id: 72, name: '骷髅' },
  { id: 73, name: '生命药水' },
  { id: 74, name: '魔力药水' },
  { id: 75, name: '汤' },
  { id: 76, name: '熟鱼' },
  { id: 77, name: '麦芽酒' },
  { id: 78, name: '剑' },
  { id: 79, name: '钓竿' },
  { id: 80, name: '虫网' },
  { id: 81, name: '雷管' },
  { id: 82, name: '迷你鲨' },
  { id: 83, name: '齿轮' },
  { id: 84, name: '墓石' },
  { id: 85, name: '金币堆' },
  { id: 86, name: '钻石戒指' },
  { id: 87, name: '困惑' },
  { id: 88, name: '亲吻' },
  { id: 89, name: '睡觉' },
  { id: 90, name: '镐' },
  { id: 91, name: '奔跑' },
  { id: 92, name: '踢人' },
  { id: 93, name: '作战' },
  { id: 94, name: '饥饿' },
  { id: 95, name: '晴朗' },
  { id: 96, name: '多云' },
  { id: 97, name: '暴风雨' },
  { id: 98, name: '暴雪' },
  { id: 99, name: '流星' },
  { id: 100, name: '火' },
  { id: 101, name: '商人' },
  { id: 102, name: '护士' },
  { id: 103, name: '军火商' },
  { id: 104, name: '树妖' },
  { id: 105, name: '向导' },
  { id: 106, name: '老人' },
  { id: 107, name: '爆破专家' },
  { id: 108, name: '服装商' },
  { id: 109, name: '哥布林工匠' },
  { id: 110, name: '巫师' },
  { id: 111, name: '机械师' },
  { id: 112, name: '圣诞老人' },
  { id: 113, name: '松露人' },
  { id: 114, name: '蒸汽朋克人' },
  { id: 115, name: '染料商' },
  { id: 116, name: '派对女孩' },
  { id: 117, name: '机器侠' },
  { id: 118, name: '油漆工' },
  { id: 119, name: '巫医' },
  { id: 120, name: '海盗' },
  { id: 121, name: '发型师' },
  { id: 122, name: '旅商' },
  { id: 123, name: '渔夫' },
  { id: 124, name: '骷髅商人' },
  { id: 125, name: '税收官' },
  { id: 126, name: '礼物' },
  { id: 127, name: '气球' },
  { id: 128, name: '蛋糕' },
  { id: 129, name: '派对帽' },
  { id: 130, name: '酒馆老板' },
  { id: 131, name: '啤酒' },
  { id: 132, name: '护卫奖章' },
  { id: 133, name: '撒旦军队' },
  { id: 134, name: '难过' },
  { id: 135, name: '抓狂' },
  { id: 136, name: '快乐' },
  { id: 137, name: '眨眼' },
  { id: 138, name: '皱眉' },
  { id: 139, name: '呆萌' },
  { id: 140, name: '高尔夫球手' },
  { id: 141, name: '动物学家' },
  { id: 142, name: '动物学家狐狸' },
  { id: 143, name: '光之女皇' },
  { id: 144, name: '史莱姆皇后' },
  { id: 145, name: '公主' },
  { id: 146, name: '稍饿' },
  { id: 147, name: '饥饿' },
  { id: 148, name: '极饿' },
  { id: 149, name: '露西' },
  { id: 150, name: '独眼巨鹿' }
]
